// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/VeIcon/SvgIcon.vue')['default']
    VeCheckboxGroup: typeof import('./src/components/VeCheckbox/VeCheckboxGroup.vue')['default']
    VeDialog: typeof import('./src/components/VeDialog/VeDialog.vue')['default']
    VeDrawer: typeof import('./src/components/VeDrawer/VeDrawer.vue')['default']
    VeForm: typeof import('./src/components/VeForm/VeForm.vue')['default']
    VeFormItem: typeof import('./src/components/VeForm/components/VeFormItem.vue')['default']
    VeIcon: typeof import('./src/components/VeIcon/VeIcon.vue')['default']
    VeRadioGroup: typeof import('./src/components/VeRadio/VeRadioGroup.vue')['default']
    VeSelect: typeof import('./src/components/VeSelect/index.vue')['default']
    VeTable: typeof import('./src/components/VeTable/VeTable.vue')['default']
  }
}

export {}
